server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083/
          predicates:
            - Path=/user/**
        - id: chat-service
          uri: http://localhost:8084/
          predicates:
            - Path=/chat/**