spring:
  application:
    name: user-service
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka